// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI10SKvRYgk4XHlDqj-7UjtkQifMGHgOI',
    appId: '1:126576698879:web:8477735cac3b239da9b3ca',
    messagingSenderId: '126576698879',
    projectId: 'smartinterestx-caf0a',
    authDomain: 'smartinterestx-caf0a.firebaseapp.com',
    storageBucket: 'smartinterestx-caf0a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt3gTXtzwktiwRznyRDZEi5KNh-LyWUFs',
    appId: '1:126576698879:android:2beaf6d31a220ee9a9b3ca',
    messagingSenderId: '126576698879',
    projectId: 'smartinterestx-caf0a',
    storageBucket: 'smartinterestx-caf0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcQV891RaCqU0IOr-WSMutN8j4lfy3icc',
    appId: '1:126576698879:ios:332b0b7099ad62e5a9b3ca',
    messagingSenderId: '126576698879',
    projectId: 'smartinterestx-caf0a',
    storageBucket: 'smartinterestx-caf0a.firebasestorage.app',
    iosBundleId: 'com.unlox.smartInterestx',
  );
}
